// =============================================================================
// File   : project/m3/rtl/top.sv
// Module : bnn_top
//
// Description
// -----------
// Integration top module for the BNN XNOR-Popcount hardware accelerator chiplet.
// Instantiates the M2 AXI4-Stream slave interface (axis_interface) and the M2
// pipelined compute core (compute_core), connects them, adds on-chip weight
// memory with a sideband load port, a runtime-configurable tile FSM, and an
// AXI4-Stream master interface for returning accumulator results to the host.
//
// Data flow (runtime, steady-state):
//   Host ARM CPU
//     → AXI4-Stream slave (axis_interface)
//     → compute_core (XNOR-Popcount, pipelined 3 cycles)
//     → tile FSM (accum_clear + result capture)
//     → AXI4-Stream master output
//     → Host ARM CPU
//
// Weight memory:
//   Weights are stored in a 1512-entry × 256-bit on-chip register file.
//   They are loaded once at startup (or at day/night context swap) via the
//   sideband write port (w_en / w_addr / w_data).  At runtime the weight
//   address counter (w_ptr) walks through weight memory in sync with each
//   activation beat accepted by the compute core.
//
// Tile control (runtime configurable):
//   One "tile" = one BNN filter applied to one spatial position.
//   cfg_beats_per_tile sets the number of 256-bit activation beats per tile:
//     conv2 (32 in-ch,  3×3): ceil(32×9 / 256)  = 2 beats
//     conv3 (64 in-ch,  3×3): ceil(64×9 / 256)  = 3 beats
//     conv4 (128 in-ch, 3×3): ceil(128×9 / 256) = 5 beats
//   The host writes cfg_beats_per_tile once per layer transition.
//   After cfg_beats_per_tile accepted beats the accumulator result is pushed
//   onto the AXI4-Stream master and accum_clear is issued for the next tile.
//   The 3-cycle pipeline latency of compute_core is tracked by a shift
//   register so that accum_clear fires exactly when the last beat has
//   retired from the pipeline.
//
// Glue logic between axis_interface and compute_core:
//   - core_data  (axis_interface → compute_core act_in): direct wire
//   - core_valid (axis_interface → compute_core s_valid): direct wire
//   - core_ready (compute_core s_ready → axis_interface): direct wire
//   - weight_in  (weight_mem[w_ptr] → compute_core): registered 1 cycle
//     ahead to keep it aligned with act_in through the pipeline
//   - accum_clear: generated by tile FSM, delayed 2 cycles to align with
//     pipeline retirement
//
// Port Descriptions
// -----------------
// clk                 in   1      System clock, rising-edge active (300 MHz target).
// rst                 in   1      Active-high synchronous reset.
//
// -- AXI4-Stream Slave (activation input from host) --
// s_axis_tvalid       in   1      Upstream activation data valid.
// s_axis_tready       out  1      This module ready to accept activations.
// s_axis_tdata        in   256    Packed 1-bit activation vector.
// s_axis_tlast        in   1      Last beat of the current frame.
//
// -- AXI4-Stream Master (result output to host) --
// m_axis_tvalid       out  1      Result word is valid.
// m_axis_tready       in   1      Host is ready to accept a result.
// m_axis_tdata        out  32     Signed 32-bit dot-product result.
// m_axis_tlast        out  1      Always asserted with m_axis_tvalid (1 result/tile).
//
// -- Weight sideband load port --
// w_en                in   1      Write enable: load one weight word this cycle.
// w_addr              in   11     Word address in weight memory (0..1511).
// w_data              in   256    Weight word to write.
//
// -- Runtime configuration --
// cfg_beats_per_tile  in   4      Activation beats per filter tile (1..15).
//                                 Set to 2 for conv2, 3 for conv3, 5 for conv4.
//                                 Sampled at the start of each new tile.
//
// -- Status --
// tile_count          out  16     Number of completed tiles since last reset.
// =============================================================================

`timescale 1ns/1ps
`default_nettype none

module bnn_top #(
    parameter int VECTOR_WIDTH = 256,   // XNOR vector width (bits)
    parameter int WEIGHT_DEPTH = 1512,  // total 256-bit weight words on chip
    parameter int MAX_BEATS    = 5      // maximum beats per tile (sizes the counter)
) (
    input  logic        clk,
    input  logic        rst,

    // AXI4-Stream Slave — activation input
    input  logic        s_axis_tvalid,
    output logic        s_axis_tready,
    input  logic [VECTOR_WIDTH-1:0] s_axis_tdata,
    input  logic        s_axis_tlast,

    // AXI4-Stream Master — result output
    output logic        m_axis_tvalid,
    input  logic        m_axis_tready,
    output logic [31:0] m_axis_tdata,
    output logic        m_axis_tlast,

    // Weight sideband load port
    input  logic        w_en,
    input  logic [$clog2(WEIGHT_DEPTH)-1:0] w_addr,
    input  logic [VECTOR_WIDTH-1:0] w_data,

    // Runtime tile configuration — set once per layer, sampled at tile start
    input  logic [3:0]  cfg_beats_per_tile,   // 1–15; use 2/3/5 for conv2/3/4

    // Status
    output logic [15:0] tile_count
);

    // =========================================================================
    // Internal signals (declared early to avoid forward-reference errors)
    // =========================================================================
    logic        core_valid;
    logic        core_ready;
    logic [VECTOR_WIDTH-1:0] core_data;
    logic        frame_done;

    // =========================================================================
    // Weight memory  (1512 × 256-bit register file)
    // =========================================================================
    logic [VECTOR_WIDTH-1:0] weight_mem [0:WEIGHT_DEPTH-1];
    logic [VECTOR_WIDTH-1:0] weight_word;

    always_ff @(posedge clk) begin
        if (w_en)
            weight_mem[w_addr] <= w_data;
    end

    // =========================================================================
    // Weight address counter
    // Advances on every accepted activation beat; wraps at WEIGHT_DEPTH.
    // =========================================================================
    localparam int W_ADDR_W = $clog2(WEIGHT_DEPTH);
    logic [W_ADDR_W-1:0] w_ptr;

    always_ff @(posedge clk) begin
        if (rst)
            w_ptr <= '0;
        else if (core_valid && core_ready) begin
            if (w_ptr == W_ADDR_W'(WEIGHT_DEPTH - 1))
                w_ptr <= '0;
            else
                w_ptr <= w_ptr + 1'b1;
        end
    end

    // Combinational read: weight_word tracks w_ptr immediately so it is
    // aligned with act_in on the same beat entering the compute_core.
    assign weight_word = weight_mem[w_ptr];

    // =========================================================================
    // axis_interface instantiation (M2, AXI4-Stream slave side)
    // =========================================================================
    axis_interface u_axis_if (
        .aclk          (clk),
        .aresetn       (~rst),
        .s_axis_tvalid (s_axis_tvalid),
        .s_axis_tready (s_axis_tready),
        .s_axis_tdata  (s_axis_tdata),
        .s_axis_tlast  (s_axis_tlast),
        .core_valid    (core_valid),
        .core_ready    (core_ready),
        .core_data     (core_data),
        .frame_done    (frame_done)
    );

    // =========================================================================
    // Tile beat counter
    // Counts accepted beats within the current tile (0 .. cfg_beats_per_tile-1).
    // cfg_beats_per_tile is latched at tile start so a mid-tile config change
    // cannot corrupt an in-progress accumulation.
    // =========================================================================
    localparam int BEAT_CTR_W = $clog2(MAX_BEATS + 1);
    logic [BEAT_CTR_W-1:0] beat_ctr;
    logic [3:0]             beats_this_tile;  // latched at start of each tile
    logic                   last_beat;        // pulses on the final accepted beat

    assign last_beat = (beat_ctr == BEAT_CTR_W'(beats_this_tile - 1))
                        && core_valid && core_ready;

    always_ff @(posedge clk) begin
        if (rst) begin
            beat_ctr       <= '0;
            beats_this_tile <= 4'd5;   // safe default (conv4)
        end else if (core_valid && core_ready) begin
            if (last_beat) begin
                beat_ctr        <= '0;
                beats_this_tile <= cfg_beats_per_tile;  // latch for next tile
            end else begin
                beat_ctr <= beat_ctr + 1'b1;
            end
        end else if (beat_ctr == '0) begin
            // Not yet started: latch config so it is ready when first beat arrives.
            beats_this_tile <= cfg_beats_per_tile;
        end
    end

    // =========================================================================
    // Pipeline delay shift register (3 cycles = compute_core latency)
    // last_beat_r3 fires exactly when the accumulator has retired the last beat.
    // =========================================================================
    logic last_beat_r1, last_beat_r2, last_beat_r3;

    always_ff @(posedge clk) begin
        if (rst) begin
            last_beat_r1 <= 1'b0;
            last_beat_r2 <= 1'b0;
            last_beat_r3 <= 1'b0;
        end else begin
            last_beat_r1 <= last_beat;
            last_beat_r2 <= last_beat_r1;
            last_beat_r3 <= last_beat_r2;
        end
    end

    // =========================================================================
    // compute_core instantiation (pipelined 3 cycles)
    // accum_clear fires the cycle after last_beat_r3 (result already captured).
    // =========================================================================
    logic signed [31:0] accum_out;
    logic               accum_clear;

    always_ff @(posedge clk)
        accum_clear <= rst ? 1'b0 : last_beat_r3;

    compute_core #(
        .VECTOR_WIDTH(VECTOR_WIDTH)
    ) u_core (
        .clk        (clk),
        .rst        (rst),
        .s_valid    (core_valid),
        .s_ready    (core_ready),
        .accum_clear(accum_clear),
        .act_in     (core_data),
        .weight_in  (weight_word),
        .accum_out  (accum_out)
    );

    // =========================================================================
    // AXI4-Stream master output (1-deep register slice)
    // Captures accum_out on last_beat_r2; holds until host asserts tready.
    // =========================================================================
    logic [31:0] result_reg;
    logic        result_valid;

    always_ff @(posedge clk) begin
        if (rst) begin
            result_reg   <= '0;
            result_valid <= 1'b0;
        end else begin
            if (last_beat_r3 && (!result_valid || m_axis_tready)) begin
                // Capture new result (whether or not previous was just consumed).
                result_reg   <= accum_out;
                result_valid <= 1'b1;
            end else if (result_valid && m_axis_tready) begin
                // Host consumed; no new result this cycle.
                result_valid <= 1'b0;
            end
        end
    end

    assign m_axis_tvalid = result_valid;
    assign m_axis_tdata  = result_reg;
    assign m_axis_tlast  = result_valid;

    // =========================================================================
    // Tile counter (status)
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst)
            tile_count <= '0;
        else if (last_beat_r3)
            tile_count <= tile_count + 1'b1;
    end

endmodule

`default_nettype wire
